package com.pubapp.model;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="newuser")
public class NewUser {

	
	private String Uid;
	@DynamoDBAttribute(attributeName="uname")
	private String Uname;
	@DynamoDBAttribute(attributeName="uemail")
	private String Uemail;
	@DynamoDBAttribute(attributeName="upassword")
	private long Upassword;
	
	
	

	private int lastapplicationid;
	
	
	
	
	
	public int getLastapplicationid() {
		return lastapplicationid;
	}

	public void setLastapplicationid(int lastapplicationid) {
		this.lastapplicationid = lastapplicationid;
	}


	@DynamoDBAttribute(attributeName="uphonenumber")
	private int uphonenumber;
	@DynamoDBAttribute(attributeName="applicationtab")
	public List<ApplicationTab>applicationtab;
	
	public List<ApplicationTab> getApplicationtab() {
		return applicationtab;
	}

	public void setApplicationtab(List<ApplicationTab> applicationtab) {
		this.applicationtab = applicationtab;
	}


	//private Date Createdate;
	@DynamoDBAttribute(attributeName="date")
	Date date =new Date();



	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="uid")
	public String getUid() {
		return Uid;
	}

	public void setUid(String uid) {
		Uid = uid;
	}

	public String getUname() {
		return Uname;
	}

	public void setUname(String uname) {
		Uname = uname;
	}

	public String getUemail() {
		return Uemail;
	}

	public void setUemail(String uemail) {
		Uemail = uemail;
	}

	public long getUpassword() {
		return Upassword;
	}

	public void setUpassword(long upassword) {
		Upassword = upassword;
	}

	
	public int getUphonenumber() {
		return uphonenumber;
	}

	public void setUphonenumber(int uphonenumber) {
		this.uphonenumber = uphonenumber;
	}

	@Override
	public String toString() {
		return "NewUser [Uid=" + Uid + ", Uname=" + Uname + ", Uemail=" + Uemail + ", Upassword=" + Upassword
				+ ", lastapplicationid=" + lastapplicationid + ", uphonenumber=" + uphonenumber + ", applicationtab="
				+ applicationtab + ", date=" + date + "]";
	}

	
	
	
	
}
